# Generated by Django 4.2.7 on 2023-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine_tuning_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
